### ISSUE TITLE
Prepare Sharding

### ISSUE THREAD

**Issue by zenril** [nullabork/talkbot#29]
Prepare Sharding. 
Load balancing wont work as all connections are open all the time.
Process Sharding...

I'm thinking load the bot with a shard range parameter
```
for(i in servers.count/20)
     forever app/bot.js --shard-from i --shard-to i+20

```

**Comment by wootosmash** [comment]
This is now implemented in the beta bot using --shard_number=n --total_shards=max(n)+1

eg. 
node bot.js --shard_number=0 --total_shards=1 (default situation)
node bot.js --shard_number=1 --total_shards=2 (run two shards, this process is the second shard)
