### ISSUE TITLE
Filter out long nonsensical repeating characters

### ISSUE THREAD

**Issue by zenril** [nullabork/talkbot#6]
maybe have a command `!stripAt 5`
```
var message = "abcdefghijklmnooooooopqrstuvwxyz".split('');


var leaveOneRemaining = true;
var thresholdToStartStriping = 4;


var lastletter = '';
var stripLength = leaveOneRemaining?0:1;
for (var i = message.length; i > 0; i--) {
    var letter = message[i - 1];

    if (lastletter == letter) {
        stripLength++;
    } else if (stripLength > thresholdToStartStriping) {
        message.splice(i, stripLength);
        stripLength = leaveOneRemaining?0:1;;
    } else {
        stripLength = leaveOneRemaining?0:1;;
    }
    lastletter = letter;
}

message = message.join('');
```

The above will return `abcdefghijklmnopqrstuvwxyz`

**Comment by zenril** [comment]
Although maybe its easier to set a larger harder threshold.
Maybe need to rework the code to detect repeating dumb patterns, if possible to do in a way that won't remove needed text.

**Comment by zenril** [comment]
I want the least data flowing through my server as possible :D i'm not to bothered but maybe betetr to optimise now, than later if it takes off

**Comment by wootosmash** [comment]
This is now implemented as stripRepeatingChars()
